name: 'Cancel this build'
description: 'Uses the GitHub Actions API to cancel the build'
inputs:
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
  message:
    description: "Message about the cancellation."
    required: true
    default: "Cancelling Workflow"
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'cloud-snow'
  color: 'blue'
outputs:
  message:
    description: "Message about the cancellation."