name: Cancel this workflow

on: push

jobs:
  Cancel:
    name: Use this repo action to cancel this workflow
    runs-on: ubuntu-latest
    steps:
      - name: Use the action
        uses: Opentrons/cancel-action@v0.8
        with:
          message: "Look the message works."
